tbl_Contacts={
        {0,"Michael"},
        {1,"Franklin"},
        {2,"Trevor"},
        {3,"Multiplayer"},
        {4,"Conference"},
        {5,"Conference"},
        {6,"Conference"},
        {7,"Conference"},
        {8,"Conference"},
        {9,"Conference"},
        {10,"Conference"},
        {11,"Conference"},
        {12,"Lester"},
        {13,"Lester Deathwish"},
        {14,"Jimmy"},
        {15,"Tracey"},
        {16,"Abigail"},
        {17,"Amanda"},
        {18,"Simeon"},
        {19,"Lamar"},
        {20,"Ron"},
        {21,"Cheng Jr."},
        {22,"CEO Assistant"},
        {23,"Steve"},
        {24,"Wade"},
        {25,"Tennis Coach"},
        {26,"Solomon"},
        {27,"Lazlow"},
        {28,"Estate Agent"},
        {29,"Devin"},
        {30,"Dave"},
        {31,"Martin"},
        {32,"Floyd"},
        {33,"Military Hitcher"},
        {34,"Oscar"},
        {35,"Cheng Sr."},
        {36,"Dr. Friedlander"},
        {37,"Stretch"},
        {38,"Ortega"},
        {39,"O'Neil"},
        {40,"Patricia"},
        {41,"Pegasus"},
        {42,"Lifeinvader"},
        {43,"Tanisha"},
        {44,"Denise"},
        {45,"Molly"},
        {46,"Rickie"},
        {47,"Chef"},
        {48,"Blimp"},
        {49,"Barry"},
        {50,"Beverly"},
        {51,"Cris"},
        {52,"Dom"},
        {53,"Hao"},
        {54,"Cletus"},
        {55,"Jimmy Boston"},
        {56,"Joe"},
        {57,"Josef"},
        {58,"Josh"},
        {59,"Manuel"},
        {60,"Marnie"},
        {61,"Mary Ann"},
        {62,"Maude"},
        {63,"Mrs Thornhill"},
        {64,"Nigel"},
        {65,"Beast"},
        {66,"Ashley"},
        {67,"Andreas"},
        {68,"Dreyfuss"},
        {69,"Omega"},
        {70,"Al Carter"},
        {71,"The Boss"},
        {72,"Edgar Claros"},
        {73,"The Boss"},
        {74,"Assistant"},
        {75,"Assistant"},
        {76,"Agent 14"},
        {77,"Stretch"},
        {78,"Corey Parker"},
        {79,"Captain"},
        {81,"Benny's Original Motor Works"},
        {82,"SecuroServ"},
        {83,"GTA Online Contact"},
        {84,"Brucie"},
        {85,"Merryweather"},
        {86,"Gerald"},
        {87,"Vanilla Unicorn"},
        {88,"Detonate Bomb"},
        {89,"Mechanic"},
        {90,"Julio Fabrizio"},
        {91,"Mors Mutual Insurance"},
        {92,"Domestic Girl"},
        {93,"Ursula"},
        {94,"Fixed Car"},
        {95,"Antonia"},
        {96,"Los Santos Customs"},
        {97,"Ammu-Nation"},
        {98,"Social Club"},
        {99,"LS Tourist Board"},
        {100,"Mechanic"},
        {101,"Sonar Collections"},
        {102,"Chop"},
        {103,"Tonya"},
        {104,"Juliet"},
        {105,"Nikki"},
        {106,"Chastity"},
        {107,"Cheetah"},
        {108,"Sapphire"},
        {109,"Infernus"},
        {110,"Fufu"},
        {111,"Peach"},
        {112,"Liz"},
        {113,"Downtown Cab Co."},
        {114,"Cinema Doppler"},
        {115,"Ten Cent Theater"},
        {116,"Tivoli Cinema"},
        {117,"Car Scrapyard"},
        {118,"Smoke on the Water"},
        {119,"Tequi-la-la"},
        {120,"Pitchers"},
        {121,"The Hen House"},
        {122,"Hookies"},
        {123,"Los Santos Golf Club"},
        {124,"Los Santos Customs"},
        {125,"Towing Impound"},
        {126,"McKenzie Field Hangar"},
        {127,"Sonar Collections Dock"},
        {128,"Detonate"},
        {129,"Jay Norris"},
        {130,"Emergency Services"},
        {131,"Downtown Cab Co."},
        {132,"Chat Call"},
        {133,"Space Monkey"},
        {134,"Isaac"},
        {135,"Castro"},
        {136,"Unknown"},
        {137,"Unknown"},
        {138,"Legendary Motorsport"},
        {139,"DockTease"},
        {140,"Warstock"},
        {141,"Elitas Travel"},
        {142,"P&M Cycles"},
        {143,"Southern SA Super Autos"},
        {144,"Virtual MP"},
        {146,"Acting Up"},
        {147,"Malc"},
        {148,"LJT"},
        {149,"Maze Bank"},
        {150,"vanderlinde@eyefind.com"},
        {151,"Tony"},
        {152,"Lazlow"},
        {153,"English Dave"},
        {154,"Paige"},
        {155,"Arena War"},
        {156,"Bryony"},
        {157,"Ms. Baker"},
        {158,"Tom Connors"},
        {159,"Hardcore Comic Store"},
        {160,"The Diamond Casino & Resort"},
        {163,"Tao's Translator"},
        {164,"Wendy"},
}
tbl_BlacklistContacts={
    {12,"Lester"},
    {76,"Agent 14"},
    {79,"Captain"},
    {148,"LJT"},
    {157,"Ms. Baker"}
}